version: "3.8"
services:

  mongodb:
    image: mongo:latest
    container_name: easyshop-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - easyshop
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  migration:
    build:
      context: .
      dockerfile: scripts/Dockerfile.migration
    container_name: easyshop-migration
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - easyshop

  main-shop:
    build:
      context: .
    container_name: easyshop-ctr
    ports:
      - "3000:3000"
    networks:
      - easyshop
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - easyshop
    restart: unless-stopped

networks:
  easyshop:
volumes:
  mongo-data:
