apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easy-shop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easy-shop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://13.221.190.156/api"
  NEXTAUTH_URL: "https://13.221.190.156/"
