kind: Secret
apiVersion: v1
metadata:
  name: easyshop-secrets
  namespace: easy-shop
type: Opaque
stringData:
    JWT_SECRET: "5c30561d1a931389b6528a9c2d0647bec899241fee6748ff7aa159a141cd4505"
    NEXTAUTH_SECRET: "bTe4wvdG4Fza9cvkpeoaAi3hEQfBslMkHRlV9rTTppM="
